# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\"$\n\x07\x43ommand\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"\xf6\x01\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04plot\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12\x0f\n\x07runtime\x18\x04 \x01(\x05\x12\r\n\x05rated\x18\x05 \x01(\t\x12\x0c\n\x04\x63\x61st\x18\x06 \x03(\t\x12\x0e\n\x06poster\x18\x07 \x01(\t\x12\r\n\x05title\x18\x08 \x01(\t\x12\x10\n\x08\x66ullplot\x18\t \x01(\t\x12\x0c\n\x04year\x18\n \x01(\x05\x12\x0c\n\x04type\x18\x0b \x01(\t\x12\x0f\n\x07writers\x18\x0c \x03(\t\x12\x11\n\tcountries\x18\r \x03(\t\x12\x11\n\tlanguages\x18\x0e \x03(\t\x12\x11\n\tdirectors\x18\x0f \x03(\t\"$\n\nMoviesList\x12\x16\n\x06movies\x18\x01 \x03(\x0b\x32\x06.Movieb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=16
  _COMMAND._serialized_end=52
  _MOVIE._serialized_start=55
  _MOVIE._serialized_end=301
  _MOVIESLIST._serialized_start=303
  _MOVIESLIST._serialized_end=339
# @@protoc_insertion_point(module_scope)
